version: '3.8'
services:
  serverless:
    build:
      context: ./docker/serverless
    volumes:
      - type: bind
        source: ./src/serverless
        target: /home/app
    environment:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
