version: '3.8'
services:
  backend:
    build:
      context: ./docker/backend
    volumes:
      - type: bind
        source: ./src/backend
        target: /home/app
    environment:
        - TZ=Asia/Tokyo
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
